services:
  mongodb:
    image: mongo:7
    container_name: sahanvi-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - sahanvi_mongo_data:/data/db

volumes:
  sahanvi_mongo_data:
